### PR TITLE
feature/streamer-report

### PR DESCRIPTION
**Pull request by dkarchmer**
New package to help users generate StreamerReports compatible with ArchFX Cloud.

New classes based on existing coretool classes but with changes to make more consistent with ArchFX Cloud without having to break the old IOTile Cloud format
- `ArchFXDataPoint` to represent a `StreamData` record
- `ArchReport` as based clase in case we have other formats in the future
- `ArchFXFlexibleDictionaryReport` to represent current mp report

Main changes with the coretools version:

- Merge `events` and `data` into a single list of `ArchFXDataPoint`
- Remove `raw_time` and `time_base` and rename `reading_time` as `timestamp`
- Allow `stream` to be an int or a string, and use `ArchFXVariableID` to parse
- Rename `uuid` with `device` and allow it to be a string or int, and use `ArchFXDeviceSlug` to parse
- Rename `streamer_local_id` as `dev_seqid` to match cloud
- Allow timestamp to be passed as timezone aware or naive `datetime`
- Add missing `value` and allow `summary_data` to be null
- Rename `device_sent_timestamp` to `sent_timestamp` and change to require `datetime` (This needs a small adjustment on the cloud)

**NOTE** that I will need to make a couple minor adjustments in the cloud before I can merge this and it can be used, but that's a small detail

### CODE REVIEW

**Comment by dkarchmer** [comment]
@timburke @mattrunchey @anwu Note that it may not be that easy for the Broker to switch to this due to the current dependency on coretool APIs that may be expecting the old class types, but this will help others anyway as it is common for somebody to need to generate and upload streamer reports for testing. May be worth to migrate some of the other functionality in the `IOTileCloud` coretools class, as I think there is only a couple of methods that are used by the broker.

**Review by timburke — APPROVED** [review]

**Comment by mattrunchey** [comment]
Opened an issue to remind us about switching the broker uploader here https://archsys.atlassian.net/browse/AFX-757

**Comment by anwu** [comment]
Looks good to me.

In AFX-749, you mentioned that having all the data in the report was not meant to be all events. So when we update the broker's uploader again, should we be making the data points that were originally `IOTileReading`s (that got turned into `IOTileEvent`s) into `ArchFXDataPoint`s with null `summary_data` and valid `value` fields?

**Review by anwu — APPROVED** [review]

**Comment by dkarchmer** [comment]
@anwu 
> So when we update the broker's uploader again, should we be making the data points that were originally IOTileReadings (that got turned into IOTileEvents) into ArchFXDataPoints with null summary_data and valid value fields?

Yes, the new `ArchFXDataPoints` combines both the same way the cloud actually stores it on the database, and yes, this is why the `summary_data` will now be optional so for anything that used to go to `IOTileReadings`, you will simply set the `value` and ignore the `summary_data`. What we DON'T want (and should actually add an assert) is to have `value` as a field in `summary_data`

**Pull request merged**
